### ISSUE TITLE
Support for Logstash 2.0

### ISSUE THREAD

**Issue by tuukkamustonen** [codekitchen/logstash-input-kinesis#7] opened 2015-11-20 07:11 UTC
Apparently the plugin is not supported on logstash 2.0? At least the documentation mentions only logstash 1.5.

**Comment by codekitchen** [comment] 2015-11-20 16:07
Somebody will need to try it, I haven't gotten any reports either way yet. I don't see anything in the "breaking changes" documentation that sounds like it would definitely break this plugin. My company is still using Logstash 1.5 though, so I haven't tested it yet.

**Comment by mtvx** [comment] 2015-11-20 18:25
I actually tested it today on logstash 2.0 and it _seemed_ to work. Unfortunately, I cannot say for sure, because I bumped into a logstash bug and had to revert back to 1.5...

**Comment by cpliakas** [comment] 2016-01-15 15:27
Awesome plugin. Love it.

I tried it out v1.4.1 of this plugin with Logstash 2.1.1, and the good news is that it seems to mostly work as I am able to consume messages from Kinesis and insert them into elasticsearch. The only issue I have encountered is restarting logstash, which I think is related to this plugin although I haven't dug in too deep. The log messages that make me think this are below:

```
{:timestamp=>"2016-01-15T15:16:21.448000+0000", :message=>"SIGTERM received. Shutting down the pipeline.", :level=>:warn}
{:timestamp=>"2016-01-15T15:16:26.455000+0000", :level=>:warn, "INFLIGHT_EVENT_COUNT"=>{"total"=>0}, "STALLING_THREADS"=>{["LogStash::Inputs::Kinesis", {"kinesis_stream_name"=>"mystream", "application_name"=>"myapp", "region"=>"us-east-1", "codec"=><LogStash::Codecs::JSON charset=>"UTF-8">}]=>[{"thread_id"=>16, "name"=>"<kinesis", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-kinesis-1.4.1-java/lib/logstash/inputs/kinesis.rb:75:in `run'"}]}}
{:timestamp=>"2016-01-15T15:16:26.459000+0000", :message=>"The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.", :level=>:error}
```

Unfortunately the `logstash.err` file is empty, so this is all the information I can find.

Again, thanks for an outstanding plugin.

**Comment by codekitchen** [comment] 2016-01-15 16:51
Hm, we attempt to teardown cleanly with https://github.com/codekitchen/logstash-input-kinesis/blob/master/lib/logstash/inputs/kinesis.rb#L89 , 5 seconds should be plenty of time to do so. I wonder if that callback isn't sufficient anymore.

**Comment by cpliakas** [comment] 2016-01-15 17:17
Interesting. Just some more information to share, the `:level=>:warn, "INFLIGHT_EVENT_COUNT"=>{"total"=>0}, "STALLING_THREADS"=>...` message repeats infinitely. Now that you mention it, messages appear every 5 seconds or so until you manually kill the logstash pid.

As a side note in case it helps someone, the following command is how I killed the pid: `ps aux | fgrep logstash | awk '/^logstash/ {print $2}' | xargs kill -9`. None of the usual suspects e.g. `killall` worked for me, maybe there is an easier way that I am missing.

**Comment by corycomer** [comment] 2016-01-15 22:21
I started using this plugin recently as well on Logstash 2.1.1 and so far, so good. I haven't experienced the issues with restarts like @cpliakas has. This is what I see when restarting logstash:

```
# service logstash restart
Killing logstash (pid 12768) with SIGTERM
Waiting logstash (pid 12768) to die...
Waiting logstash (pid 12768) to die...
Waiting logstash (pid 12768) to die...
Waiting logstash (pid 12768) to die...
Waiting logstash (pid 12768) to die...
Timeout reached. Killing logstash (pid 12768) with SIGKILL. This may result in data loss.
logstash killed with SIGKILL.
logstash started.
```

and from the logstash.log I see, 

```
{:timestamp=>"2016-01-15T22:15:00.040000+0000", :message=>"kinesis plugin is using the 'milestone' method to declare the version of the plugin this method is deprecated in favor of declaring the version inside the gemspec.", :level=>:warn}
{:timestamp=>"2016-01-15T22:15:10.844000+0000", :message=>"SIGTERM received. Shutting down the pipeline.", :level=>:warn}
{:timestamp=>"2016-01-15T22:15:20.658000+0000", :message=>"kinesis plugin is using the 'milestone' method to declare the version of the plugin this method is deprecated in favor of declaring the version inside the gemspec.", :level=>:warn}
```

```
bin/logstash --version
logstash 2.1.1
```

@cpliakas are you using any other plugins or outputs?

**Comment by cpliakas** [comment] 2016-01-17 19:08
No other plugins or outputs. It is a really simple setup right now. My logstash configuration is below:

```
input {
    kinesis {
        kinesis_stream_name => "mystream"
        application_name => "myapp"
        region => "us-east-1"
        codec => json { }
    }
}

output {
    elasticsearch {
        hosts => ["elasticsearch.internal:9200"]
    }
}
```

The snippet below is how I install logstash in my Packer template, which is built from an Ubuntu 14.04 AMI provided by canonical:

``` shell
export DEBIAN_FRONTEND=noninteractive

wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
echo 'deb http://packages.elasticsearch.org/logstash/2.1/debian stable main' | sudo tee /etc/apt/sources.list.d/logstash.list

sudo add-apt-repository -y ppa:brightbox/ruby-ng
sudo apt-add-repository -y ppa:webupd8team/java
sudo apt-get update
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
sudo apt-get install --no-install-recommends -y logstash oracle-java8-installer ruby2.2

sudo /opt/logstash/bin/plugin install logstash-input-kinesis
```

Don't judge on the Ruby PPA, haven't gotten around to doing a more ruby-ish solution i.e. rbenv. I did try using Ruby 2.0, but I got the same behavior.

Usually stuff like this is because I am doing something stupid, so that is my assumption here, but I haven't figured out what that is just yet.

**Comment by corycomer** [comment] 2016-01-18 19:52
@cpliakas I just caught the INFLIGHT_EVENTS_COUNT warning today during some testing. I did some decent testing over the weekend and it looks like it appeared one other time, but only those two occurances, 

```
{:timestamp=>"2016-01-18T19:08:59.221000+0000", :message=>"SIGTERM received. Shutting down the pipeline.", :level=>:warn}
{:timestamp=>"2016-01-18T19:09:08.880000+0000", :message=>"kinesis plugin is using the 'milestone' method to declare the version of the plugin this method is deprecated in favor of declaring the version inside the gemspec.", :level=>:warn}
{:timestamp=>"2016-01-18T19:11:08.372000+0000", :message=>"SIGTERM received. Shutting down the pipeline.", :level=>:warn}
{:timestamp=>"2016-01-18T19:11:13.376000+0000", :level=>:warn, "INFLIGHT_EVENT_COUNT"=>{"total"=>0}, "STALLING_THREADS"=>{["LogStash::Inputs::Kinesis", {"kinesis_stream_name"=>"redacted", "region"=>"us-west-2", "codec"=><LogStash::Codecs::JSON charset=>"UTF-8">, "metrics"=>"cloudwatch"}]=>[{"thread_id"=>18, "name"=>"<kinesis", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-kinesis-1.4.1-java/lib/logstash/inputs/kinesis.rb:75:in `run'"}]}}
{:timestamp=>"2016-01-18T19:11:18.182000+0000", :message=>"kinesis plugin is using the 'milestone' method to declare the version of the plugin this method is deprecated in favor of declaring the version inside the gemspec.", :level=>:warn}
{:timestamp=>"2016-01-18T19:14:09.905000+0000", :message=>"SIGTERM received. Shutting down the pipeline.", :level=>:warn}
{:timestamp=>"2016-01-18T19:18:06.957000+0000", :message=>"kinesis plugin is using the 'milestone' method to declare the version of the plugin this method is deprecated in favor of declaring the version inside the gemspec.", :level=>:warn}
{:timestamp=>"2016-01-18T19:31:49.896000+0000", :message=>"SIGTERM received. Shutting down the pipeline.", :level=>:warn}
```

I assume you might have the following in your /etc/default/logstash 

```
# If this is set to 1, then when `stop` is called, if the process has
# not exited within a reasonable time, SIGKILL will be sent next.
# The default behavior is to simply log a message "program stop failed; still running"
#KILL_ON_STOP_TIMEOUT=1
```

I enabled this because there were times that logstash was taking 30-60 seconds to stop (sometimes not stopping at all) so you might be seeing some kind of bug with the way logstash handles plugins during a shutdown. Here's the issue where the option was added https://github.com/elastic/logstash/issues/3578 but I imagine there are many many causes for logstash to either be slow when shutting down or not able to shutdown completely.

I haven't noticed any issues with restarting logstash like this when using this plugin, if it's an option, I'd recommend at least enabling this so you can get a clean shutdown during restarts. As for the root cause, not sure! Good luck :)

**Comment by cpliakas** [comment] 2016-01-19 12:18
@corycomer This is awesome information. Thanks for taking the time to guide me in the right direction, I will definitely try that setting out.

As you mentioned, seems like a Logstash issue. Since my first post to this thread the plugin has been running happily in my environment on Logstash 2.1.1. The Kinesis stream is being processed, logs are getting into Elasticsearch in near-real time.

**Comment by codekitchen** [comment] 2016-01-21 17:18
I've updated the README to say this plugin works with Logstash >= 1.5, since it sounds like it is working with 2.1 as well. I'm going to close this issue, we can always file a new issue for anything specific that crops up.

**Closed as completed by codekitchen** 2016-01-21 17:18 UTC
